#!/usr/bin/env bash
# Applies the configuration file located in $file_newconfig to $file_config
# Usage: script.sh

# Configuration file
file_config=/etc/v2ray/config.json
# The new configuration file generated by add_user.sh del_user.sh ...
file_newconfig=/root/v2ray_tools/config.json_new
# Where to store a backup from your current running configuration file
file_oldconfig=/root/v2ray_tools/config.json_old
# File storing all the users that were deleted the last time you ran del_user.sh
file_deleted=/root/v2ray_tools/deleted

cp "$file_config" "$file_oldconfig"
cp "$file_newconfig" "$file_config"
cat "${file_deleted}_pending" >> "$file_deleted"
